### ISSUE TITLE
line-awesome not found

### ISSUE THREAD

**Issue by simasch** [vaadin/starters#125]
If I create a new Vaadin project I get this exception:

```
java.lang.IllegalStateException: Asset '/line-awesome/dist/line-awesome/css/line-awesome.min.css' is not found in project frontend directory, default development bundle or in the application bundle 'src/main/dev-bundle/assets/'. 
Verify that the asset is available in 'frontend/themes/vaadin/' directory and is added into the 'assets' block of the 'theme.json' file.
	at com.vaadin.flow.server.StaticFileServer.findAssetInFrontendThemesOrDevBundle(StaticFileServer.java:374) ~[flow-server-24.0.6.jar:24.0.6]
	at com.vaadin.flow.server.StaticFileServer.serveStaticResource(StaticFileServer.java:273) ~[flow-server-24.0.6.jar:24.0.6]
	at com.vaadin.flow.server.VaadinServlet.serveStaticOrWebJarRequest(VaadinServlet.java:431) ~[flow-server-24.0.6.jar:24.0.6]
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:386) ~[flow-server-24.0.6.jar:24.0.6]
	at com.vaadin.flow.spring.SpringServlet.service(SpringServlet.java:106) ~[vaadin-spring-24.0.6.jar:na]
```

**Comment by Artur-** [comment]
If I create a new Vaadin project, I see no exceptions. There is no reference to `line-awesome.min.css` in the project either

**Comment by Artur-** [comment]
Ealier, line awesome was included through the theme but now it is used through 
```
        <dependency>
            <groupId>org.parttio</groupId>
            <artifactId>line-awesome</artifactId>
            <version>1.1.0</version>
        </dependency>
```

**Comment by simasch** [comment]
I retried it and now it works. Probably there was something messed up with an existing project.
