### ISSUE TITLE
Starters tests have i18n problems

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/starters#13]
**Describe the bug**
Downloaded the latest LTS bakery app starter and tried to run the StorefronViewIT integration test. The test failed due to my language setting. The required field error message is localized based on the browser's language setting, but the test is always checking for English error messages - mine is German and thus make the test fail.

**Log**
```
org.junit.ComparisonFailure: 
Expected :must not be blank
Actual   :darf nicht leer sein
<Click to see difference>

	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.vaadin.stefan.testbench.StorefrontViewIT.testClearRequiredField(StorefrontViewIT.java:123)
	at org.vaadin.stefan.testbench.StorefrontViewIT.testTextFieldValidation(StorefrontViewIT.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
```

**To Reproduce**
0. Setup your OS to not use English.
1. Download the bakery app starter.
2. Configure your environment properly to run tests.
3. Run the StorefrontViewIT.

**Expected behavior**
The tests should be language independent or the chrome driver should be initialized to use "en" for tests.

**Environment (please complete the following information):**
 - Starter name: Bakery app
 - OS: Windows 10, German
 - Browser: Chrome
 - Vaadin version: 14.1.28

**Comment by stefanuebe** [comment]
Workaround: Switching my OS and Chrome language to english solved that.

**Comment by samie** [comment]
Would that be something that could be done in Chrome parameters?

**Comment by anasmi** [comment]
I am not sure this is a bug. More like an enhancement to make tests works on different locals.

**Comment by samie** [comment]
Maybe we should just change the test to use and override in English only?
