### ISSUE TITLE
java.lang.ClassNotFoundException when i start a new start.vaadin.com app

### ISSUE THREAD

**Issue by jcgueriaud1** [vaadin/starters#21]
**Describe the bug**
When I run the application downloaded from the starter, I have this exception.
The application is still running.
```
2021-07-14 11:06:21.989  INFO 2747 --- [  restartedMain] com.example.application.Application      : Started Application in 10.258 seconds (JVM running for 10.628)
Exception in thread "restartedMain" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: java.lang.NoClassDefFoundError: com/vaadin/flow/server/startup/ApplicationConfiguration
	at org.vaadin.artur.helpers.LaunchUtil.isProductionMode(LaunchUtil.java:37)
	at org.vaadin.artur.helpers.LaunchUtil.launchBrowserInDevelopmentMode(LaunchUtil.java:100)
	at com.example.application.Application.main(Application.java:18)
	... 5 more
Caused by: java.lang.ClassNotFoundException: com.vaadin.flow.server.startup.ApplicationConfiguration
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 8 more
```

I choose Flow app and download.
Then I run `mvn package` and `mvn spring-boot:run`

I attached the application downloaded
[test-start.zip](https://github.com/vaadin/starters/files/6814546/test-start.zip)

**Comment by Artur-** [comment]
This has been fixed
